"""add x credential table

Revision ID: 023da4906612
Revises: 4f07a59c3b9c
Create Date: 2025-02-19 13:43:33.061780

"""
from typing import Sequence, Union
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa
prepend_sys_path = "."


# revision identifiers, used by Alembic.
revision: str = '023da4906612'
down_revision: Union[str, None] = '4f07a59c3b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('app_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consumer_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consumer_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bearer_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_credentials')
    # ### end Alembic commands ###
