"""add token_following col

Revision ID: 1d950663358d
Revises: 753d35823a35
Create Date: 2025-04-03 07:21:15.445892

"""
from typing import Sequence, Union
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa
prepend_sys_path = "."
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d950663358d'
down_revision: Union[str, None] = '753d35823a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_followings', sa.Column('network', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('token_followings', 'follow_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token_followings', 'follow_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('token_followings', 'network')
    # ### end Alembic commands ###
