"""add personas table

Revision ID: 4f07a59c3b9c
Revises: d4d733847c8c
Create Date: 2025-02-18 17:57:06.727328

"""
from typing import Sequence, Union
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa
prepend_sys_path = "."


# revision identifiers, used by Alembic.
revision: str = '4f07a59c3b9c'
down_revision: Union[str, None] = 'd4d733847c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profession', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('financial_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('personality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('likes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dislikes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('posting_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('daily_post_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_personas')
    # ### end Alembic commands ###
