"""add x language to persona table

Revision ID: 559da8107ae0
Revises: 78082ac64750
Create Date: 2025-02-24 14:39:52.874105

"""
from typing import Sequence, Union
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa
prepend_sys_path = "."


# revision identifiers, used by Alembic.
revision: str = '559da8107ae0'
down_revision: Union[str, None] = '78082ac64750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_credentials', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_credentials', 'language')
    # ### end Alembic commands ###
