"""add token_following col

Revision ID: 7371d10a8c48
Revises: 1d950663358d
Create Date: 2025-04-03 07:43:17.282243

"""
from typing import Sequence, Union
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa
prepend_sys_path = "."


# revision identifiers, used by Alembic.
revision: str = '7371d10a8c48'
down_revision: Union[str, None] = '1d950663358d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_followings', sa.Column('called_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_followings', 'called_price')
    # ### end Alembic commands ###
