"""add token_following table

Revision ID: 753d35823a35
Revises: b020e38ffab9
Create Date: 2025-04-03 07:17:25.281824

"""
from typing import Sequence, Union
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa
prepend_sys_path = "."


# revision identifiers, used by Alembic.
revision: str = '753d35823a35'
down_revision: Union[str, None] = 'b020e38ffab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_followings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('follow_at', sa.DateTime(), nullable=False),
    sa.Column('follow_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_followings')
    # ### end Alembic commands ###
