"""add x username to persona table

Revision ID: acf6db3dfb72
Revises: 023da4906612
Create Date: 2025-02-21 13:18:44.318192

"""
from typing import Sequence, Union
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa
prepend_sys_path = "."


# revision identifiers, used by Alembic.
revision: str = 'acf6db3dfb72'
down_revision: Union[str, None] = '023da4906612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_personas', sa.Column('twitter_app_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_personas', 'twitter_app_id')
    # ### end Alembic commands ###
