"""add personas table

Revision ID: d4d733847c8c
Revises: 6e858956bdff
Create Date: 2025-02-18 17:54:45.257950

"""
from typing import Sequence, Union
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa
prepend_sys_path = "."


# revision identifiers, used by Alembic.
revision: str = 'd4d733847c8c'
down_revision: Union[str, None] = '6e858956bdff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
